services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: reviewinbox
      POSTGRES_USER: reviewinbox
      POSTGRES_PASSWORD: reviewinbox
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/data:/var/lib/postgresql
