import { defineConfig } from 'oxlint'

export default defineConfig({
  categories: { correctness: 'error', pedantic: 'error', perf: 'error', suspicious: 'error' },
  ignorePatterns: [
    '.agent/**',
    '.agents/**',
    '.claude/**',
    '.codex/**',
    '.continue/**',
    '.cursor/**',
    '.gemini/**',
    '.opencode/**',
    '.pi/**',
    '.roo/**',
    '.windsurf/**',
    '.nx/**',
    '.angular/**',
    '**/.astro/**',
    'volumes/**',
    'packages/db/migrations/**',
    'coverage/**',
    'dist/**',
    'node_modules/**',
  ],
  jsPlugins: [
    { name: 'anti-slop', specifier: 'oxlint-plugin-anti-slop' },
    { name: 'sonarjs', specifier: 'eslint-plugin-sonarjs' },
  ],
  options: { maxWarnings: 0, reportUnusedDisableDirectives: 'error', typeAware: true },
  plugins: ['eslint', 'typescript', 'unicorn', 'oxc', 'import', 'node', 'promise', 'vitest'],
  rules: {
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
    complexity: ['error', { max: 10, variant: 'classic' }],
    curly: ['error', 'all'],
    // Import count does not measure module cohesion; enforce responsibility through review.
    'import/max-dependencies': 'off',
    // Stylesheet imports are required side effects in Angular and Astro entry points.
    'import/no-unassigned-import': ['error', { allow: ['**/*.css'] }],
    'max-classes-per-file': ['error', 2],
    'max-depth': ['error', 3],
    'max-lines': 'off',
    'max-lines-per-function': ['error', { max: 50, skipBlankLines: true, skipComments: true }],
    'max-params': ['error', 4],
    'max-statements': ['error', { max: 12 }],
    'no-nested-ternary': 'error',
    'no-console': 'error',
    'sonarjs/cognitive-complexity': ['error', 15],
    'sonarjs/no-all-duplicated-branches': 'error',
    'sonarjs/no-duplicated-branches': 'error',
    'sonarjs/no-identical-functions': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-non-null-assertion': 'error',
    'typescript/prefer-readonly-parameter-types': 'off',
  },
  overrides: [
    {
      files: ['test/**/*.ts', '**/*.test.ts', '**/*.spec.ts'],
      rules: {
        'max-lines-per-function': ['error', { max: 80, skipBlankLines: true, skipComments: true }],
        'max-statements': ['error', { max: 20 }],
      },
    },
  ],
})
