packages:
  - apps/*
  - packages/*

overrides:
  better-call: 1.3.6

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true

minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2102.16'
  - '@angular-devkit/core@21.2.16'
  - '@angular-devkit/schematics@21.2.16'
  - '@angular/build@21.2.16'
  - '@angular/cli@21.2.16'
  - '@schematics/angular@21.2.16'
  - ngx-better-auth@1.6.2
