packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@3.0.128'
  - '@ai-sdk/provider-utils@4.0.28'
  - '@turbo/darwin-64@2.9.18'
  - '@turbo/darwin-arm64@2.9.18'
  - '@turbo/linux-64@2.9.18'
  - '@turbo/linux-arm64@2.9.18'
  - '@turbo/windows-64@2.9.18'
  - '@turbo/windows-arm64@2.9.18'
  - '@types/node@25.9.3'
  - ai@6.0.202
  - turbo@2.9.18
