/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingFirstOwnerRouteImport } from './routes/onboarding/first-owner'
import { Route as ApiOnboardingFirstOwnerRouteImport } from './routes/api/onboarding/first-owner'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFirstOwnerRoute = OnboardingFirstOwnerRouteImport.update({
  id: '/onboarding/first-owner',
  path: '/onboarding/first-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingFirstOwnerRoute = ApiOnboardingFirstOwnerRouteImport.update({
  id: '/api/onboarding/first-owner',
  path: '/api/onboarding/first-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/onboarding/first-owner': typeof OnboardingFirstOwnerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/first-owner': typeof ApiOnboardingFirstOwnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/onboarding/first-owner': typeof OnboardingFirstOwnerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/first-owner': typeof ApiOnboardingFirstOwnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/onboarding/first-owner': typeof OnboardingFirstOwnerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/onboarding/first-owner': typeof ApiOnboardingFirstOwnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/onboarding/first-owner'
    | '/api/auth/$'
    | '/api/onboarding/first-owner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/onboarding/first-owner'
    | '/api/auth/$'
    | '/api/onboarding/first-owner'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/onboarding/first-owner'
    | '/api/auth/$'
    | '/api/onboarding/first-owner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  OnboardingFirstOwnerRoute: typeof OnboardingFirstOwnerRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOnboardingFirstOwnerRoute: typeof ApiOnboardingFirstOwnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/first-owner': {
      id: '/onboarding/first-owner'
      path: '/onboarding/first-owner'
      fullPath: '/onboarding/first-owner'
      preLoaderRoute: typeof OnboardingFirstOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/first-owner': {
      id: '/api/onboarding/first-owner'
      path: '/api/onboarding/first-owner'
      fullPath: '/api/onboarding/first-owner'
      preLoaderRoute: typeof ApiOnboardingFirstOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  OnboardingFirstOwnerRoute: OnboardingFirstOwnerRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOnboardingFirstOwnerRoute: ApiOnboardingFirstOwnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
